/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoginBharti4510RouteImport } from './routes/login-bharti-4510'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as RecruiterCompanyRouteImport } from './routes/recruiter.company'
import { Route as RecruiterCompanyBharti4510RouteImport } from './routes/recruiter.company-bharti-4510'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as RecruiterInterviewsRouteImport } from './routes/recruiter.interviews'
import { Route as RecruiterShortlistedRouteImport } from './routes/recruiter.shortlisted'
import { Route as RecruiterShortlistedBharti4510RouteImport } from './routes/recruiter.shortlisted-bharti-4510'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as StudentAiAssistantRouteImport } from './routes/student.ai-assistant'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentLearningRouteImport } from './routes/student.learning'
import { Route as StudentMentorshipRouteImport } from './routes/student.mentorship'
import { Route as StudentOnboardingRouteImport } from './routes/student.onboarding'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as RecruiterOpportunitiesIndexRouteImport } from './routes/recruiter.opportunities.index'
import { Route as RecruiterOpportunitiesIdRouteImport } from './routes/recruiter.opportunities.$id'
import { Route as RecruiterOpportunitiesIdBharti4510RouteImport } from './routes/recruiter.opportunities.$id-bharti-4510'
import { Route as RecruiterOpportunitiesNewRouteImport } from './routes/recruiter.opportunities.new'
import { Route as RecruiterTalentIndexRouteImport } from './routes/recruiter.talent.index'
import { Route as RecruiterTalentCandidateIdRouteImport } from './routes/recruiter.talent.$candidateId'
import { Route as StudentOpportunitiesIndexRouteImport } from './routes/student.opportunities.index'
import { Route as StudentOpportunitiesIdRouteImport } from './routes/student.opportunities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBharti4510Route = LoginBharti4510RouteImport.update({
  id: '/login-bharti-4510',
  path: '/login-bharti-4510',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/admin/resources',
  path: '/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterCompanyRoute = RecruiterCompanyRouteImport.update({
  id: '/recruiter/company',
  path: '/recruiter/company',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterCompanyBharti4510Route =
  RecruiterCompanyBharti4510RouteImport.update({
    id: '/recruiter/company-bharti-4510',
    path: '/recruiter/company-bharti-4510',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/recruiter/dashboard',
  path: '/recruiter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterInterviewsRoute = RecruiterInterviewsRouteImport.update({
  id: '/recruiter/interviews',
  path: '/recruiter/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterShortlistedRoute = RecruiterShortlistedRouteImport.update({
  id: '/recruiter/shortlisted',
  path: '/recruiter/shortlisted',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterShortlistedBharti4510Route =
  RecruiterShortlistedBharti4510RouteImport.update({
    id: '/recruiter/shortlisted-bharti-4510',
    path: '/recruiter/shortlisted-bharti-4510',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAiAssistantRoute = StudentAiAssistantRouteImport.update({
  id: '/student/ai-assistant',
  path: '/student/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/student/applications',
  path: '/student/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLearningRoute = StudentLearningRouteImport.update({
  id: '/student/learning',
  path: '/student/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMentorshipRoute = StudentMentorshipRouteImport.update({
  id: '/student/mentorship',
  path: '/student/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOnboardingRoute = StudentOnboardingRouteImport.update({
  id: '/student/onboarding',
  path: '/student/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterOpportunitiesIndexRoute =
  RecruiterOpportunitiesIndexRouteImport.update({
    id: '/recruiter/opportunities/',
    path: '/recruiter/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterOpportunitiesIdRoute =
  RecruiterOpportunitiesIdRouteImport.update({
    id: '/recruiter/opportunities/$id',
    path: '/recruiter/opportunities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterOpportunitiesIdBharti4510Route =
  RecruiterOpportunitiesIdBharti4510RouteImport.update({
    id: '/recruiter/opportunities/$id-bharti-4510',
    path: '/recruiter/opportunities/$id-bharti-4510',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterOpportunitiesNewRoute =
  RecruiterOpportunitiesNewRouteImport.update({
    id: '/recruiter/opportunities/new',
    path: '/recruiter/opportunities/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterTalentIndexRoute = RecruiterTalentIndexRouteImport.update({
  id: '/recruiter/talent/',
  path: '/recruiter/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterTalentCandidateIdRoute =
  RecruiterTalentCandidateIdRouteImport.update({
    id: '/recruiter/talent/$candidateId',
    path: '/recruiter/talent/$candidateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentOpportunitiesIndexRoute =
  StudentOpportunitiesIndexRouteImport.update({
    id: '/student/opportunities/',
    path: '/student/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentOpportunitiesIdRoute = StudentOpportunitiesIdRouteImport.update({
  id: '/student/opportunities/$id',
  path: '/student/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/login-bharti-4510': typeof LoginBharti4510Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/company-bharti-4510': typeof RecruiterCompanyBharti4510Route
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/shortlisted-bharti-4510': typeof RecruiterShortlistedBharti4510Route
  '/register/student': typeof RegisterStudentRoute
  '/student/ai-assistant': typeof StudentAiAssistantRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/mentorship': typeof StudentMentorshipRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/register/': typeof RegisterIndexRoute
  '/recruiter/opportunities/$id': typeof RecruiterOpportunitiesIdRoute
  '/recruiter/opportunities/$id-bharti-4510': typeof RecruiterOpportunitiesIdBharti4510Route
  '/recruiter/opportunities/new': typeof RecruiterOpportunitiesNewRoute
  '/recruiter/talent/$candidateId': typeof RecruiterTalentCandidateIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
  '/recruiter/opportunities/': typeof RecruiterOpportunitiesIndexRoute
  '/recruiter/talent/': typeof RecruiterTalentIndexRoute
  '/student/opportunities/': typeof StudentOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/login-bharti-4510': typeof LoginBharti4510Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/company-bharti-4510': typeof RecruiterCompanyBharti4510Route
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/shortlisted-bharti-4510': typeof RecruiterShortlistedBharti4510Route
  '/register/student': typeof RegisterStudentRoute
  '/student/ai-assistant': typeof StudentAiAssistantRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/mentorship': typeof StudentMentorshipRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/register': typeof RegisterIndexRoute
  '/recruiter/opportunities/$id': typeof RecruiterOpportunitiesIdRoute
  '/recruiter/opportunities/$id-bharti-4510': typeof RecruiterOpportunitiesIdBharti4510Route
  '/recruiter/opportunities/new': typeof RecruiterOpportunitiesNewRoute
  '/recruiter/talent/$candidateId': typeof RecruiterTalentCandidateIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
  '/recruiter/opportunities': typeof RecruiterOpportunitiesIndexRoute
  '/recruiter/talent': typeof RecruiterTalentIndexRoute
  '/student/opportunities': typeof StudentOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/login-bharti-4510': typeof LoginBharti4510Route
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/company-bharti-4510': typeof RecruiterCompanyBharti4510Route
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/shortlisted': typeof RecruiterShortlistedRoute
  '/recruiter/shortlisted-bharti-4510': typeof RecruiterShortlistedBharti4510Route
  '/register/student': typeof RegisterStudentRoute
  '/student/ai-assistant': typeof StudentAiAssistantRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/mentorship': typeof StudentMentorshipRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/register/': typeof RegisterIndexRoute
  '/recruiter/opportunities/$id': typeof RecruiterOpportunitiesIdRoute
  '/recruiter/opportunities/$id-bharti-4510': typeof RecruiterOpportunitiesIdBharti4510Route
  '/recruiter/opportunities/new': typeof RecruiterOpportunitiesNewRoute
  '/recruiter/talent/$candidateId': typeof RecruiterTalentCandidateIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
  '/recruiter/opportunities/': typeof RecruiterOpportunitiesIndexRoute
  '/recruiter/talent/': typeof RecruiterTalentIndexRoute
  '/student/opportunities/': typeof StudentOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/login-bharti-4510'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/opportunities'
    | '/admin/resources'
    | '/admin/users'
    | '/admin/verifications'
    | '/recruiter/company'
    | '/recruiter/company-bharti-4510'
    | '/recruiter/dashboard'
    | '/recruiter/interviews'
    | '/recruiter/shortlisted'
    | '/recruiter/shortlisted-bharti-4510'
    | '/register/student'
    | '/student/ai-assistant'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/mentorship'
    | '/student/onboarding'
    | '/student/profile'
    | '/register/'
    | '/recruiter/opportunities/$id'
    | '/recruiter/opportunities/$id-bharti-4510'
    | '/recruiter/opportunities/new'
    | '/recruiter/talent/$candidateId'
    | '/student/opportunities/$id'
    | '/recruiter/opportunities/'
    | '/recruiter/talent/'
    | '/student/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/login-bharti-4510'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/opportunities'
    | '/admin/resources'
    | '/admin/users'
    | '/admin/verifications'
    | '/recruiter/company'
    | '/recruiter/company-bharti-4510'
    | '/recruiter/dashboard'
    | '/recruiter/interviews'
    | '/recruiter/shortlisted'
    | '/recruiter/shortlisted-bharti-4510'
    | '/register/student'
    | '/student/ai-assistant'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/mentorship'
    | '/student/onboarding'
    | '/student/profile'
    | '/register'
    | '/recruiter/opportunities/$id'
    | '/recruiter/opportunities/$id-bharti-4510'
    | '/recruiter/opportunities/new'
    | '/recruiter/talent/$candidateId'
    | '/student/opportunities/$id'
    | '/recruiter/opportunities'
    | '/recruiter/talent'
    | '/student/opportunities'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/login-bharti-4510'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/opportunities'
    | '/admin/resources'
    | '/admin/users'
    | '/admin/verifications'
    | '/recruiter/company'
    | '/recruiter/company-bharti-4510'
    | '/recruiter/dashboard'
    | '/recruiter/interviews'
    | '/recruiter/shortlisted'
    | '/recruiter/shortlisted-bharti-4510'
    | '/register/student'
    | '/student/ai-assistant'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/mentorship'
    | '/student/onboarding'
    | '/student/profile'
    | '/register/'
    | '/recruiter/opportunities/$id'
    | '/recruiter/opportunities/$id-bharti-4510'
    | '/recruiter/opportunities/new'
    | '/recruiter/talent/$candidateId'
    | '/student/opportunities/$id'
    | '/recruiter/opportunities/'
    | '/recruiter/talent/'
    | '/student/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  LoginBharti4510Route: typeof LoginBharti4510Route
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  RecruiterCompanyRoute: typeof RecruiterCompanyRoute
  RecruiterCompanyBharti4510Route: typeof RecruiterCompanyBharti4510Route
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterInterviewsRoute: typeof RecruiterInterviewsRoute
  RecruiterShortlistedRoute: typeof RecruiterShortlistedRoute
  RecruiterShortlistedBharti4510Route: typeof RecruiterShortlistedBharti4510Route
  RegisterStudentRoute: typeof RegisterStudentRoute
  StudentAiAssistantRoute: typeof StudentAiAssistantRoute
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLearningRoute: typeof StudentLearningRoute
  StudentMentorshipRoute: typeof StudentMentorshipRoute
  StudentOnboardingRoute: typeof StudentOnboardingRoute
  StudentProfileRoute: typeof StudentProfileRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  RecruiterOpportunitiesIdRoute: typeof RecruiterOpportunitiesIdRoute
  RecruiterOpportunitiesIdBharti4510Route: typeof RecruiterOpportunitiesIdBharti4510Route
  RecruiterOpportunitiesNewRoute: typeof RecruiterOpportunitiesNewRoute
  RecruiterTalentCandidateIdRoute: typeof RecruiterTalentCandidateIdRoute
  StudentOpportunitiesIdRoute: typeof StudentOpportunitiesIdRoute
  RecruiterOpportunitiesIndexRoute: typeof RecruiterOpportunitiesIndexRoute
  RecruiterTalentIndexRoute: typeof RecruiterTalentIndexRoute
  StudentOpportunitiesIndexRoute: typeof StudentOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-bharti-4510': {
      id: '/login-bharti-4510'
      path: '/login-bharti-4510'
      fullPath: '/login-bharti-4510'
      preLoaderRoute: typeof LoginBharti4510RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/company': {
      id: '/recruiter/company'
      path: '/recruiter/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof RecruiterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/company-bharti-4510': {
      id: '/recruiter/company-bharti-4510'
      path: '/recruiter/company-bharti-4510'
      fullPath: '/recruiter/company-bharti-4510'
      preLoaderRoute: typeof RecruiterCompanyBharti4510RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/recruiter/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/interviews': {
      id: '/recruiter/interviews'
      path: '/recruiter/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof RecruiterInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/shortlisted': {
      id: '/recruiter/shortlisted'
      path: '/recruiter/shortlisted'
      fullPath: '/recruiter/shortlisted'
      preLoaderRoute: typeof RecruiterShortlistedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/shortlisted-bharti-4510': {
      id: '/recruiter/shortlisted-bharti-4510'
      path: '/recruiter/shortlisted-bharti-4510'
      fullPath: '/recruiter/shortlisted-bharti-4510'
      preLoaderRoute: typeof RecruiterShortlistedBharti4510RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/ai-assistant': {
      id: '/student/ai-assistant'
      path: '/student/ai-assistant'
      fullPath: '/student/ai-assistant'
      preLoaderRoute: typeof StudentAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/learning': {
      id: '/student/learning'
      path: '/student/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof StudentLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/mentorship': {
      id: '/student/mentorship'
      path: '/student/mentorship'
      fullPath: '/student/mentorship'
      preLoaderRoute: typeof StudentMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/onboarding': {
      id: '/student/onboarding'
      path: '/student/onboarding'
      fullPath: '/student/onboarding'
      preLoaderRoute: typeof StudentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/opportunities/': {
      id: '/recruiter/opportunities/'
      path: '/recruiter/opportunities'
      fullPath: '/recruiter/opportunities/'
      preLoaderRoute: typeof RecruiterOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/opportunities/$id': {
      id: '/recruiter/opportunities/$id'
      path: '/recruiter/opportunities/$id'
      fullPath: '/recruiter/opportunities/$id'
      preLoaderRoute: typeof RecruiterOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/opportunities/$id-bharti-4510': {
      id: '/recruiter/opportunities/$id-bharti-4510'
      path: '/recruiter/opportunities/$id-bharti-4510'
      fullPath: '/recruiter/opportunities/$id-bharti-4510'
      preLoaderRoute: typeof RecruiterOpportunitiesIdBharti4510RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/opportunities/new': {
      id: '/recruiter/opportunities/new'
      path: '/recruiter/opportunities/new'
      fullPath: '/recruiter/opportunities/new'
      preLoaderRoute: typeof RecruiterOpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/talent/': {
      id: '/recruiter/talent/'
      path: '/recruiter/talent'
      fullPath: '/recruiter/talent/'
      preLoaderRoute: typeof RecruiterTalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/talent/$candidateId': {
      id: '/recruiter/talent/$candidateId'
      path: '/recruiter/talent/$candidateId'
      fullPath: '/recruiter/talent/$candidateId'
      preLoaderRoute: typeof RecruiterTalentCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/opportunities/': {
      id: '/student/opportunities/'
      path: '/student/opportunities'
      fullPath: '/student/opportunities/'
      preLoaderRoute: typeof StudentOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/opportunities/$id': {
      id: '/student/opportunities/$id'
      path: '/student/opportunities/$id'
      fullPath: '/student/opportunities/$id'
      preLoaderRoute: typeof StudentOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  LoginBharti4510Route: LoginBharti4510Route,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  RecruiterCompanyRoute: RecruiterCompanyRoute,
  RecruiterCompanyBharti4510Route: RecruiterCompanyBharti4510Route,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterInterviewsRoute: RecruiterInterviewsRoute,
  RecruiterShortlistedRoute: RecruiterShortlistedRoute,
  RecruiterShortlistedBharti4510Route: RecruiterShortlistedBharti4510Route,
  RegisterStudentRoute: RegisterStudentRoute,
  StudentAiAssistantRoute: StudentAiAssistantRoute,
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLearningRoute: StudentLearningRoute,
  StudentMentorshipRoute: StudentMentorshipRoute,
  StudentOnboardingRoute: StudentOnboardingRoute,
  StudentProfileRoute: StudentProfileRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  RecruiterOpportunitiesIdRoute: RecruiterOpportunitiesIdRoute,
  RecruiterOpportunitiesIdBharti4510Route:
    RecruiterOpportunitiesIdBharti4510Route,
  RecruiterOpportunitiesNewRoute: RecruiterOpportunitiesNewRoute,
  RecruiterTalentCandidateIdRoute: RecruiterTalentCandidateIdRoute,
  StudentOpportunitiesIdRoute: StudentOpportunitiesIdRoute,
  RecruiterOpportunitiesIndexRoute: RecruiterOpportunitiesIndexRoute,
  RecruiterTalentIndexRoute: RecruiterTalentIndexRoute,
  StudentOpportunitiesIndexRoute: StudentOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
